const fs = require('fs');
const content = [
"'use client'",
"",
"import React, { useEffect, useState } from 'react'",
"",
"export default function HomePage() {",
"  const [visible, setVisible] = useState(false)",
"",
"  useEffect(() => {",
"    setTimeout(() => setVisible(true), 100)",
"  }, [])",
"",
"  return (",
"    <div style={{",
"      minHeight: '100vh',",
"      display: 'flex',",
"      alignItems: 'center',",
"      justifyContent: 'center',",
"      background: 'radial-gradient(circle at 50% 40%, rgba(37,99,235,0.22), transparent 60%), linear-gradient(180deg, #020617 0%, #0b1220 100%)',",
"      fontFamily: 'Arial, sans-serif',",
"      overflow: 'hidden',",
"      position: 'relative',",
"    }}>",
"      <div style={{",
"        position: 'absolute',",
"        inset: 0,",
"        background: 'radial-gradient(circle at 50% 50%, rgba(37,99,235,0.08), transparent 70%)',",
"        pointerEvents: 'none',",
"      }} />",
"      <div style={{",
"        textAlign: 'center',",
"        opacity: visible ? 1 : 0,",
"        transform: visible ? 'translateY(0)' : 'translateY(30px)',",
"        transition: 'all 1.2s ease',",
"        display: 'flex',",
"        flexDirection: 'column',",
"        alignItems: 'center',",
"        gap: 24,",
"        padding: 40,",
"      }}>",
"        <div style={{",
"          position: 'relative',",
"          marginBottom: 8,",
"        }}>",
"          <div style={{",
"            position: 'absolute',",
"            inset: -20,",
"            background: 'radial-gradient(circle, rgba(37,99,235,0.3), transparent 70%)',",
"            borderRadius: '50%',",
"            filter: 'blur(20px)',",
"          }} />",
"          <img",
"            src='/assets/logo.png'",
"            alt='BoxFlow OS'",
"            style={{",
"              width: 180,",
"              height: 180,",
"              objectFit: 'contain',",
"              position: 'relative',",
"              zIndex: 1,",
"              filter: 'drop-shadow(0 0 30px rgba(37,99,235,0.6))',",
"            }}",
"          />",
"        </div>",
"        <div>",
"          <h1 style={{",
"            margin: 0,",
"            fontSize: 64,",
"            fontWeight: 900,",
"            color: '#ffffff',",
"            letterSpacing: -1,",
"            textShadow: '0 0 40px rgba(37,99,235,0.5)',",
"            lineHeight: 1,",
"          }}>BoxFlow OS</h1>",
"          <div style={{",
"            fontSize: 18,",
"            color: '#60a5fa',",
"            fontWeight: 600,",
"            letterSpacing: 3,",
"            textTransform: 'uppercase',",
"            marginTop: 12,",
"          }}>Enterprise Operations Suite</div>",
"        </div>",
"        <div style={{",
"          display: 'flex',",
"          gap: 4,",
"          marginTop: 8,",
"        }}>",
"          {['Logistics', 'Production', 'Dispatch', 'Fleet', 'AI'].map((item, i) => (",
"            <div key={item} style={{",
"              padding: '6px 14px',",
"              borderRadius: 999,",
"              background: 'rgba(37,99,235,0.12)',",
"              border: '1px solid rgba(59,130,246,0.25)',",
"              color: '#93c5fd',",
"              fontSize: 12,",
"              fontWeight: 700,",
"              opacity: visible ? 1 : 0,",
"              transform: visible ? 'translateY(0)' : 'translateY(10px)',",
"              transition: `all 0.6s ease ${0.3 + i * 0.1}s`,",
"            }}>{item}</div>",
"          ))}",
"        </div>",
"        <a",
"          href='/login'",
"          style={{",
"            marginTop: 16,",
"            padding: '18px 48px',",
"            background: 'linear-gradient(135deg, #1d4ed8, #2563eb)',",
"            color: '#fff',",
"            borderRadius: 16,",
"            textDecoration: 'none',",
"            fontWeight: 800,",
"            fontSize: 18,",
"            letterSpacing: 0.5,",
"            boxShadow: '0 0 40px rgba(37,99,235,0.4), 0 8px 32px rgba(0,0,0,0.3)',",
"            border: '1px solid rgba(96,165,250,0.3)',",
"            transition: 'all 0.2s ease',",
"          }}",
"        >",
"          Enter System →",
"        </a>",
"        <div style={{ color: '#334155', fontSize: 12, marginTop: 8 }}>",
"          Powered by BoxFlow OS v2.0",
"        </div>",
"      </div>",
"    </div>",
"  )",
"}"
].join('\n');

fs.writeFileSync('app/page.tsx', content, 'utf8');
console.log('Splash page fixed!');