const fs = require('fs');
const lines = [];
lines.push("'use client'");
lines.push("");
lines.push("import React from 'react'");
lines.push("import AppSidebar from '@/components/AppSidebar'");
lines.push("import { supabase } from '@/lib/supabase'");
lines.push("");
lines.push("export default function OrdersPage() {");
lines.push("  const [orders, setOrders] = React.useState([])");
lines.push("  const [loading, setLoading] = React.useState(true)");
lines.push("  React.useEffect(() => {");
lines.push("    supabase.from('orders').select('*').order('created_at', { ascending: false }).then(({ data }) => {");
lines.push("      setOrders(data || [])");
lines.push("      setLoading(false)");
lines.push("    })");
lines.push("  }, [])");
lines.push("  return (");
lines.push("    <div style={{ display: 'flex', minHeight: '100vh', background: '#050816', padding: 20, gap: 24 }}>");
lines.push("      <AppSidebar active='orders' />");
lines.push("      <main style={{ flex: 1, color: '#fff', minWidth: 0 }}>");
lines.push("        <h1 style={{ fontSize: 44, fontWeight: 900, color: '#fff', marginBottom: 8 }}>Enterprise Order System</h1>");
lines.push("        <p style={{ color: '#94a3b8', marginBottom: 24 }}>Create, track, assign, and manage live orders.</p>");
lines.push("        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 14, marginBottom: 24 }}>");
lines.push("          <div style={{ background: 'rgba(15,23,42,0.95)', border: '1px solid rgba(148,163,184,0.14)', borderRadius: 22, padding: 18 }}><div style={{ color: '#64748b', fontSize: 12, marginBottom: 10, fontWeight: 700 }}>TOTAL ORDERS</div><div style={{ fontSize: 30, fontWeight: 900, color: '#fff' }}>{loading ? '...' : orders.length}</div></div>");
lines.push("          <div style={{ background: 'rgba(15,23,42,0.95)', border: '1px solid rgba(148,163,184,0.14)', borderRadius: 22, padding: 18 }}><div style={{ color: '#64748b', fontSize: 12, marginBottom: 10, fontWeight: 700 }}>OPEN / ACTIVE</div><div style={{ fontSize: 30, fontWeight: 900, color: '#fff' }}>{loading ? '...' : orders.filter(o => !['delivered','completed'].includes((o.status||'').toLowerCase())).length}</div></div>");
lines.push("          <div style={{ background: 'rgba(15,23,42,0.95)', border: '1px solid rgba(148,163,184,0.14)', borderRadius: 22, padding: 18 }}><div style={{ color: '#64748b', fontSize: 12, marginBottom: 10, fontWeight: 700 }}>RUSH ORDERS</div><div style={{ fontSize: 30, fontWeight: 900, color: '#fcd34d' }}>{loading ? '...' : orders.filter(o => ['rush','urgent'].includes((o.priority||'').toLowerCase())).length}</div></div>");
lines.push("          <div style={{ background: 'rgba(15,23,42,0.95)', border: '1px solid rgba(148,163,184,0.14)', borderRadius: 22, padding: 18 }}><div style={{ color: '#64748b', fontSize: 12, marginBottom: 10, fontWeight: 700 }}>IN TRANSIT</div><div style={{ fontSize: 30, fontWeight: 900, color: '#38bdf8' }}>{loading ? '...' : orders.filter(o => (o.status||'').toLowerCase().includes('transit')).length}</div></div>");
lines.push("        </div>");
lines.push("        <div style={{ background: 'rgba(15,23,42,0.92)', border: '1px solid rgba(148,163,184,0.14)', borderRadius: 26, overflow: 'hidden' }}>");
lines.push("          <div style={{ padding: '18px', borderBottom: '1px solid rgba(148,163,184,0.12)' }}><div style={{ fontSize: 20, fontWeight: 800, color: '#fff' }}>Live Orders Board</div></div>");
lines.push("          {loading ? <div style={{ padding: 24, color: '#94a3b8' }}>Loading orders...</div> : orders.length === 0 ? <div style={{ padding: 24, color: '#94a3b8' }}>No orders found.</div> : (");
lines.push("            <div style={{ overflowX: 'auto' }}><table style={{ width: '100%', borderCollapse: 'collapse' }}>");
lines.push("              <thead><tr style={{ background: 'rgba(2,6,23,0.35)' }}>");
lines.push("                <th style={{ padding: '14px 18px', fontSize: 12, color: '#94a3b8', textAlign: 'left', fontWeight: 800 }}>LOAD</th>");
lines.push("                <th style={{ padding: '14px 18px', fontSize: 12, color: '#94a3b8', textAlign: 'left', fontWeight: 800 }}>CLIENT</th>");
lines.push("                <th style={{ padding: '14px 18px', fontSize: 12, color: '#94a3b8', textAlign: 'left', fontWeight: 800 }}>TRUCK</th>");
lines.push("                <th style={{ padding: '14px 18px', fontSize: 12, color: '#94a3b8', textAlign: 'left', fontWeight: 800 }}>STATUS</th>");
lines.push("              </tr></thead>");
lines.push("              <tbody>{orders.map(order => (");
lines.push("                <tr key={order.id} style={{ borderTop: '1px solid rgba(148,163,184,0.1)' }}>");
lines.push("                  <td style={{ padding: '14px 18px', color: '#fff', fontWeight: 700 }}>{order.load_name || order.id}</td>");
lines.push("                  <td style={{ padding: '14px 18px', color: '#e2e8f0' }}>{order.client_name || 'N/A'}</td>");
lines.push("                  <td style={{ padding: '14px 18px', color: '#e2e8f0' }}>{order.assigned_truck_id || 'Unassigned'}</td>");
lines.push("                  <td style={{ padding: '14px 18px' }}><span style={{ padding: '5px 10px', borderRadius: 999, fontSize: 12, fontWeight: 800, background: 'rgba(59,130,246,0.14)', color: '#93c5fd', border: '1px solid rgba(59,130,246,0.3)' }}>{order.status || 'Pending'}</span></td>");
lines.push("                </tr>");
lines.push("              ))}</tbody>");
lines.push("            </table></div>");
lines.push("          )}");
lines.push("        </div>");
lines.push("      </main>");
lines.push("    </div>");
lines.push("  )");
lines.push("}");
fs.writeFileSync('app/orders/page.tsx', lines.join('\n'), 'utf8');
console.log('Orders fixed!');